language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod repo update --silent
- pod install --project-directory=PPEventRegistryAPI

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - WORKSPACE=PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace
  - SCHEME_IOS="PPEventRegistryAPI iOS"
  - SCHEME_TVOS="PPEventRegistryAPI tvOS"
  - SCHEME_WATCHOS="PPEventRegistryAPI watchOS"
  - SCHEME_MACOS="PPEventRegistryAPI macOS"
  - IOS_SDK=iphonesimulator10.0
  - WATCHOS_SDK=watchsimulator3.0
  - TVOS_SDK=appletvsimulator10.0
  - MACOS_SDK=macosx10.12
  matrix:
    - DESTINATION="name=iPhone 6s,OS=10.0"         SDK="$IOS_SDK"     SCHEME="$SCHEME_IOS"     RUN_TESTS="YES" SEND_COVERAGE="YES" POD_LINT="YES" CARTHAGE="NO"
    - DESTINATION="name=Apple Watch - 42mm,OS=3.0" SDK="$WATCHOS_SDK" SCHEME="$SCHEME_WATCHOS" RUN_TESTS="NO"  SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"
    - DESTINATION="name=Apple TV 1080p,OS=10.0"    SDK="$TVOS_SDK"    SCHEME="$SCHEME_TVOS"    RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="YES"
    - DESTINATION="arch=x86_64"                    SDK="$MACOS_SDK"   SCHEME="$SCHEME_MACOS"   RUN_TESTS="YES" SEND_COVERAGE="NO"  POD_LINT="NO"  CARTHAGE="NO"

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
    xcodebuild build-for-testing test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  else
    xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES | xcpretty -c;
  fi

- if [ $POD_LINT == "YES" ]; then
    pod lib lint;
  fi

- if [ $CARTHAGE == "YES" ]; then
    carthage build --no-skip-current;
  fi

after_success:
- test $SEND_COVERAGE = "YES" && ./.coverage.sh
